### ISSUE TITLE
Error in htmlwidgets::shinyRenderWidget: unused argument (evn = env)

### ISSUE THREAD

**Issue by ffalcolini** [Shiivong27/Business_process_mining#1]
Hi!

I tried to run the shiny app on my PC (with R Studio).

But when I click on button "Plot", I receive this error "htmlwidgets::shinyRenderWidget: unused argument (evn = env)"

I suppose this error is related to DiagramR library, but I can't to correct it.
Can you help me, please?

Thank you!

**Comment by Shiivong27** [comment]
Hi,

It's working fine on my computer. Have you tried re-installing the mentioned package(s)? 

If you want to view the application you can find it here : https://shiivong27.shinyapps.io/Process_Mining/

Do let me know if you're still facing any issues!

**Comment by ffalcolini** [comment]
Hi! 
You are really kind!
Unfortunately I tried to re-install the mentioned package several times, but it still doesn't work.

I had seen the application on shinyapp.io 
But I'd like to be able to install it locally, so I could continue your work.

Thanks again!
Francesco

**Comment by ffalcolini** [comment]
Hi!

I don't know why, but I tried to install the package again and ..... now it works!
Who knows! Maybe a problem with the mirror I am using (the Italian one).

Thanks so much!

**Comment by Shiivong27** [comment]
That's awesome!! Do let me know how it goes. Would love to see what
features you add/modify to the app. There's much room for improvement I suppose. All the best!

Regards,
Shiivong
